I=imread('C:\Users\USER\Desktop\pic\im.jpeg');
I=rgb2gray(I);
K=imnoise(I,'gaussian');
subplot(2,2,1);
p=filter2(fspecial('average',3),K)/255;
imshow(p);
title('Average filter');
subplot(2,2,2);
p=medfilt2(K);
imshow(p);
title('Median filter');
subplot(2,2,3);
p=wiener2(K,[5,5]);
imshow(p);
title('Adaptive filter');
subplot(2,2,4);
J=imnoise(I,'salt & pepper',0.02);
J=medfilt2(J);
imshow(J);
title('Salt & pepper median filter');